-- AfriScope Media — CMS v2 migration
-- No API keys or secrets are changed. This creates a stable editorial store
-- and imports the latest readable state from legacy site_data.

begin;

create table if not exists public.cms_site_state (
  id text primary key,
  categories jsonb not null default '[]'::jsonb,
  authors jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  ads jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null default '/',
  device text,
  referrer text,
  visitor_id text,
  session_id text,
  title text,
  country text,
  region text,
  city text
);

create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_visitor_idx on public.analytics_events(visitor_id);

create table if not exists public.cms_articles (
  id text primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  image text not null default '',
  seo_title text not null default '',
  seo_description text not null default '',
  og_description text not null default '',
  category text not null default '',
  author text not null default '',
  tags text[] not null default '{}',
  premium boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published','scheduled')),
  publish_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  read_minutes integer not null default 1
);

create index if not exists cms_articles_public_idx
  on public.cms_articles (status, publish_at, updated_at desc)
  where deleted_at is null;

create index if not exists cms_articles_category_idx
  on public.cms_articles (category, publish_at desc)
  where deleted_at is null;

alter table public.cms_site_state enable row level security;
alter table public.cms_articles enable row level security;
alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from anon, authenticated;
grant select on table public.analytics_events to authenticated;



drop policy if exists "cms state public read" on public.cms_site_state;
drop policy if exists "cms state admin insert" on public.cms_site_state;
drop policy if exists "cms state admin update" on public.cms_site_state;
drop policy if exists "cms state admin delete" on public.cms_site_state;

create policy "cms state public read"
  on public.cms_site_state for select
  to anon, authenticated using (id = 'main');
create policy "cms state admin insert"
  on public.cms_site_state for insert
  to authenticated with check (id = 'main');
create policy "cms state admin update"
  on public.cms_site_state for update
  to authenticated using (id = 'main') with check (id = 'main');
create policy "cms state admin delete"
  on public.cms_site_state for delete
  to authenticated using (id = 'main');

drop policy if exists "cms articles public read" on public.cms_articles;
drop policy if exists "cms articles admin read" on public.cms_articles;
drop policy if exists "cms articles admin insert" on public.cms_articles;
drop policy if exists "cms articles admin update" on public.cms_articles;
drop policy if exists "cms articles admin delete" on public.cms_articles;

create policy "cms articles public read"
  on public.cms_articles for select
  to anon
  using (
    deleted_at is null
    and (
      status = 'published'
      or (status = 'scheduled' and publish_at is not null and publish_at <= now())
    )
  );
create policy "cms articles admin read"
  on public.cms_articles for select
  to authenticated using (true);
create policy "cms articles admin insert"
  on public.cms_articles for insert
  to authenticated with check (true);
create policy "cms articles admin update"
  on public.cms_articles for update
  to authenticated using (true) with check (true);
create policy "cms articles admin delete"
  on public.cms_articles for delete
  to authenticated using (true);

drop policy if exists "analytics admin read" on public.analytics_events;
create policy "analytics admin read" on public.analytics_events for select to authenticated using (true);

-- Import the newest readable legacy state. If legacy site_data has duplicates,
-- only the newest row is used; nothing is deleted from site_data by this migration.
with latest as (
  select data
  from public.site_data
  where id = 'main'
  order by updated_at desc nulls last, ctid desc
  limit 1
), rows as (
  select value as a
  from latest, jsonb_array_elements(coalesce(latest.data->'articles','[]'::jsonb))
), normalized as (
  select
    coalesce(nullif(a->>'id',''), md5(coalesce(a->>'slug', a->>'title', gen_random_uuid()::text))) as article_id,
    coalesce(nullif(a->>'slug',''), md5(coalesce(a->>'title', gen_random_uuid()::text))) as article_slug,
    a
  from rows
), ranked as (
  select *, row_number() over (partition by article_slug order by nullif(a->>'updatedAt','')::timestamptz desc nulls last, nullif(a->>'createdAt','')::timestamptz desc nulls last) as rn
  from normalized
)
insert into public.cms_articles (
  id, slug, title, excerpt, content, image, seo_title, seo_description, og_description,
  category, author, tags, premium, status, publish_at, created_at, updated_at, deleted_at, read_minutes
)
select
  article_id,
  article_slug,
  coalesce(a->>'title','Sans titre'),
  coalesce(a->>'excerpt',''),
  coalesce(a->>'content',''),
  coalesce(a->>'image',''),
  coalesce(a->>'seoTitle', a->>'title',''),
  coalesce(a->>'seoDescription', a->>'excerpt',''),
  coalesce(a->>'ogDescription', a->>'seoDescription', a->>'excerpt',''),
  coalesce(a->>'category',''),
  coalesce(a->>'author',''),
  coalesce((select array_agg(x) from jsonb_array_elements_text(coalesce(a->'tags','[]'::jsonb)) x), '{}'),
  case when lower(coalesce(a->>'premium','false')) in ('true','1','yes') then true else false end,
  case when a->>'status' in ('published','scheduled','draft') then a->>'status' else 'draft' end,
  case when nullif(a->>'publishAt','') is null then null else (a->>'publishAt')::timestamptz end,
  coalesce(nullif(a->>'createdAt','')::timestamptz, now()),
  now(),
  case when nullif(a->>'deletedAt','') is null then null else (a->>'deletedAt')::timestamptz end,
  greatest(case when (a->>'readMinutes') ~ '^[0-9]+$' then (a->>'readMinutes')::integer else 1 end,1)
from ranked
where rn=1 and article_id is not null and article_slug is not null
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  image = excluded.image,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  og_description = excluded.og_description,
  category = excluded.category,
  author = excluded.author,
  tags = excluded.tags,
  premium = excluded.premium,
  status = excluded.status,
  publish_at = excluded.publish_at,
  created_at = excluded.created_at,
  updated_at = now(),
  deleted_at = excluded.deleted_at,
  read_minutes = excluded.read_minutes;


insert into public.cms_site_state (id) values ('main') on conflict (id) do nothing;

-- Public image bucket. Existing objects/bucket are preserved.
insert into storage.buckets (id, name, public)
values ('article-images','article-images',true)
on conflict (id) do update set public = true;

drop policy if exists "article images public read" on storage.objects;
drop policy if exists "article images admin insert" on storage.objects;
drop policy if exists "article images admin update" on storage.objects;
drop policy if exists "article images admin delete" on storage.objects;
create policy "article images public read"
  on storage.objects for select to anon, authenticated using (bucket_id='article-images');
create policy "article images admin insert"
  on storage.objects for insert to authenticated with check (bucket_id='article-images');
create policy "article images admin update"
  on storage.objects for update to authenticated using (bucket_id='article-images') with check (bucket_id='article-images');
create policy "article images admin delete"
  on storage.objects for delete to authenticated using (bucket_id='article-images');

commit;

select id, updated_at from public.cms_site_state where id='main';
select count(*) as article_count from public.cms_articles;
