project_id = "xzgxabefcyxenxlymfur"

[functions.ai-editor]
verify_jwt = true

[functions.track-visit]
verify_jwt = false

[functions.og]
verify_jwt = false

[functions.daily-newsletter]
verify_jwt = false
